import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layouts/Layout";

export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-gray-100 dark:bg-gray-700 items-center justify-center">
        <Layout children={children}/>
      </body>
    </html>
  );
}
