import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-fixed h-screen bg-gray-100 flex flex-col items-center justify-center"
      >
        {children}
      </body>
    </html>
  );
}
